import "package:ciyue/database/app/app.dart";
import "package:ciyue/models/backup/backup.dart";
import "package:ciyue/services/cloud_sync/sync_models.dart";

/// Converts a conflict-free sync snapshot back into Ciyue's local Drift data.
///
/// Tag IDs are deliberately regenerated by tag name: integer IDs are local to
/// each SQLite database and must never be copied across devices.
class CloudSyncBackupCodec {
  const CloudSyncBackupCodec();

  BackupData decode(
    SyncSnapshot snapshot, {
    List<WordbookTag> localTags = const [],
    bool allowAutoResolve = false,
  }) {
    final effectiveSnapshot = allowAutoResolve
        ? const CloudSyncEngine().resolveConflicts(snapshot)
        : snapshot;
    final merge = const CloudSyncEngine().merge(
      effectiveSnapshot,
      effectiveSnapshot,
    );
    if (merge.conflicts.isNotEmpty) {
      throw StateError(
        "Resolve ${merge.conflicts.length} sync conflict(s) before applying cloud data.",
      );
    }

    final active = effectiveSnapshot.latestRecords.where(
      (record) => !record.deleted,
    );
    final tagsByStableId = <String, String>{};
    final entries = <Map<String, Object?>>[];
    final cards = <Map<String, Object?>>[];
    final reviewLogs = <Map<String, Object?>>[];

    for (final record in active) {
      final data = record.data!;
      switch (record.entityType) {
        case "wordbook-tag":
          final name = data["name"]! as String;
          tagsByStableId[record.entityId] = name;
          break;
        case "wordbook-entry":
          entries.add(data);
          break;
        case "flashcard":
          cards.add(data);
          break;
        case "flashcard-review-log":
          reviewLogs.add(data);
          break;
      }
    }

    final tagNames = tagsByStableId.values.toSet().toList()..sort();
    final localIdsByName = <String, int>{};
    for (final tag in localTags) {
      localIdsByName.putIfAbsent(tag.tag, () => tag.id);
    }
    var nextTagId =
        localTags.fold<int>(
          0,
          (maxId, tag) => tag.id > maxId ? tag.id : maxId,
        ) +
        1;
    final tagIdsByName = <String, int>{};
    for (final name in tagNames) {
      tagIdsByName[name] = localIdsByName[name] ?? nextTagId++;
    }
    final tags = [
      for (final name in tagNames)
        WordbookTag(id: tagIdsByName[name]!, tag: name),
    ];

    final words = <WordbookData>[];
    for (final entry in entries) {
      final word = entry["word"]! as String;
      final tagName = entry["tagName"] as String?;
      final tagId = tagName == null ? null : tagIdsByName[tagName];
      if (tagName != null && tagId == null) {
        throw FormatException(
          "Word '$word' refers to missing cloud tag '$tagName'.",
        );
      }
      words.add(
        WordbookData(
          word: word,
          tag: tagId,
          createdAt: DateTime.parse(entry["createdAt"]! as String),
        ),
      );
    }

    final flashcards = cards
        .map((data) => Flashcard.fromJson(Map<String, dynamic>.from(data)))
        .toList(growable: false);
    final logs = reviewLogs
        .map(
          (data) => FlashcardReviewLog.fromJson({
            ...data,
            // The SQLite autoincrement ID is local and isn't part of sync.
            "id": 0,
          }),
        )
        .toList(growable: false);

    words.sort((a, b) {
      final wordOrder = a.word.compareTo(b.word);
      if (wordOrder != 0) return wordOrder;
      return (a.tag ?? 0).compareTo(b.tag ?? 0);
    });
    flashcards.sort((a, b) => a.word.compareTo(b.word));
    logs.sort((a, b) {
      final dateOrder = a.reviewedAt.compareTo(b.reviewedAt);
      if (dateOrder != 0) return dateOrder;
      final wordOrder = a.word.compareTo(b.word);
      if (wordOrder != 0) return wordOrder;
      return a.rating.compareTo(b.rating);
    });

    return BackupData(
      version: BackupData.currentVersion,
      wordbookWords: words,
      wordbookTags: tags,
      flashcards: flashcards,
      flashcardReviewLogs: logs,
    );
  }
}
