#!/bin/sh
HERE=$(dirname "$(readlink -f "$0")")
cd "$HERE"
export LD_LIBRARY_PATH="$HERE/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export XDG_DATA_DIRS="$HERE/usr/share:$HERE/share:$XDG_DATA_DIRS"
exec "$HERE/ciyue" "$@"
